// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexoraAPI.Models;

#nullable disable

namespace NexoraAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706122536_RedesignSkillsAndAddCourseSkillTags")]
    partial class RedesignSkillsAndAddCourseSkillTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexoraAPI.Models.Assessment", b =>
                {
                    b.Property<int>("IdAssessment")
                        .HasColumnType("int")
                        .HasColumnName("id_assessment");

                    b.Property<string>("AssessmentType")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("assessment_type");

                    b.Property<string>("CodeModule")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_module");

                    b.Property<string>("CodePresentation")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_presentation");

                    b.Property<string>("Date")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("date");

                    b.HasKey("IdAssessment")
                        .HasName("PK__assessme__0A74B8277284752F");

                    b.HasIndex("CodeModule", "CodePresentation");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.Course", b =>
                {
                    b.Property<string>("CodeModule")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_module");

                    b.Property<string>("CodePresentation")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_presentation");

                    b.HasKey("CodeModule", "CodePresentation");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.CourseSkillTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeModule")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("CodePresentation")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Beginner");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodeModule", "CodePresentation");

                    b.ToTable("CourseSkillTags", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentAssessment", b =>
                {
                    b.Property<int?>("DateSubmitted")
                        .HasColumnType("int")
                        .HasColumnName("date_submitted");

                    b.Property<int?>("IdAssessment")
                        .HasColumnType("int")
                        .HasColumnName("id_assessment");

                    b.Property<int?>("IdStudent")
                        .HasColumnType("int")
                        .HasColumnName("id_student");

                    b.Property<byte?>("IsBanked")
                        .HasColumnType("tinyint")
                        .HasColumnName("is_banked");

                    b.Property<double?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.HasIndex("IdAssessment");

                    b.ToTable("studentAssessment", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentInfo", b =>
                {
                    b.Property<string>("CodeModule")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_module");

                    b.Property<string>("CodePresentation")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_presentation");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int")
                        .HasColumnName("id_student");

                    b.Property<string>("AgeBand")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("age_band");

                    b.Property<string>("Disability")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("disability");

                    b.Property<string>("FinalResult")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("final_result");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("gender");

                    b.Property<string>("HighestEducation")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("highest_education");

                    b.Property<string>("ImdBand")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("imd_band");

                    b.Property<int?>("NumOfPrevAttempts")
                        .HasColumnType("int")
                        .HasColumnName("num_of_prev_attempts");

                    b.Property<string>("Region")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("region");

                    b.Property<int?>("StudiedCredits")
                        .HasColumnType("int")
                        .HasColumnName("studied_credits");

                    b.HasKey("CodeModule", "CodePresentation", "IdStudent");

                    b.ToTable("studentInfo", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentRegistration", b =>
                {
                    b.Property<string>("CodeModule")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_module");

                    b.Property<string>("CodePresentation")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_presentation");

                    b.Property<int?>("DateRegistration")
                        .HasColumnType("int")
                        .HasColumnName("date_registration");

                    b.Property<int?>("DateUnregistration")
                        .HasColumnType("int")
                        .HasColumnName("date_unregistration");

                    b.Property<int?>("IdStudent")
                        .HasColumnType("int")
                        .HasColumnName("id_student");

                    b.HasIndex("CodeModule", "CodePresentation", "IdStudent");

                    b.ToTable("studentRegistration", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Beginner");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StudentSkills", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentVle", b =>
                {
                    b.Property<string>("CodeModule")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_module");

                    b.Property<string>("CodePresentation")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_presentation");

                    b.Property<int?>("Date")
                        .HasColumnType("int")
                        .HasColumnName("date");

                    b.Property<int?>("IdSite")
                        .HasColumnType("int")
                        .HasColumnName("id_site");

                    b.Property<int?>("IdStudent")
                        .HasColumnType("int")
                        .HasColumnName("id_student");

                    b.Property<int?>("SumClick")
                        .HasColumnType("int")
                        .HasColumnName("sum_click");

                    b.HasIndex("IdSite");

                    b.HasIndex("CodeModule", "CodePresentation", "IdStudent");

                    b.ToTable("studentVle", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.Vle", b =>
                {
                    b.Property<int>("IdSite")
                        .HasColumnType("int")
                        .HasColumnName("id_site");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("activity_type");

                    b.Property<string>("CodeModule")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_module");

                    b.Property<string>("CodePresentation")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code_presentation");

                    b.Property<string>("WeekFrom")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("week_from");

                    b.Property<string>("WeekTo")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("week_to");

                    b.HasKey("IdSite")
                        .HasName("PK__vle__4594B5E6AC690155");

                    b.HasIndex("CodeModule", "CodePresentation");

                    b.ToTable("vle", (string)null);
                });

            modelBuilder.Entity("NexoraAPI.Models.Assessment", b =>
                {
                    b.HasOne("NexoraAPI.Models.Course", "Course")
                        .WithMany("Assessments")
                        .HasForeignKey("CodeModule", "CodePresentation")
                        .HasConstraintName("FK__assessments__398D8EEE");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("NexoraAPI.Models.CourseSkillTag", b =>
                {
                    b.HasOne("NexoraAPI.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CodeModule", "CodePresentation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("NexoraAPI.Models.Notification", b =>
                {
                    b.HasOne("NexoraAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentAssessment", b =>
                {
                    b.HasOne("NexoraAPI.Models.Assessment", "IdAssessmentNavigation")
                        .WithMany()
                        .HasForeignKey("IdAssessment")
                        .HasConstraintName("FK__studentAs__id_as__4316F928");

                    b.Navigation("IdAssessmentNavigation");
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentInfo", b =>
                {
                    b.HasOne("NexoraAPI.Models.Course", "Course")
                        .WithMany("StudentInfos")
                        .HasForeignKey("CodeModule", "CodePresentation")
                        .IsRequired()
                        .HasConstraintName("FK__studentInfo__3F466844");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentRegistration", b =>
                {
                    b.HasOne("NexoraAPI.Models.StudentInfo", "StudentInfo")
                        .WithMany()
                        .HasForeignKey("CodeModule", "CodePresentation", "IdStudent")
                        .HasConstraintName("FK__studentRegistrat__412EB0B6");

                    b.Navigation("StudentInfo");
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentSkill", b =>
                {
                    b.HasOne("NexoraAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexoraAPI.Models.StudentVle", b =>
                {
                    b.HasOne("NexoraAPI.Models.Vle", "IdSiteNavigation")
                        .WithMany()
                        .HasForeignKey("IdSite")
                        .HasConstraintName("FK__studentVl__id_si__45F365D3");

                    b.HasOne("NexoraAPI.Models.StudentInfo", "StudentInfo")
                        .WithMany()
                        .HasForeignKey("CodeModule", "CodePresentation", "IdStudent")
                        .HasConstraintName("FK__studentVle__44FF419A");

                    b.Navigation("IdSiteNavigation");

                    b.Navigation("StudentInfo");
                });

            modelBuilder.Entity("NexoraAPI.Models.User", b =>
                {
                    b.HasOne("NexoraAPI.Models.StudentInfo", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .HasPrincipalKey("IdStudent");
                });

            modelBuilder.Entity("NexoraAPI.Models.Vle", b =>
                {
                    b.HasOne("NexoraAPI.Models.Course", "Course")
                        .WithMany("Vles")
                        .HasForeignKey("CodeModule", "CodePresentation")
                        .HasConstraintName("FK__vle__3C69FB99");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("NexoraAPI.Models.Course", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("StudentInfos");

                    b.Navigation("Vles");
                });
#pragma warning restore 612, 618
        }
    }
}
